language: ruby
bundler_args: --without doc
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0
  - 2.1
  - rbx
  - rbx-2
  - jruby
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
notifications:
  email:
    - github@elskwid.net
